module.exports = {
  content: ['./src/**/*.{html,js,ts,jsx,tsx}', './index.html'],
  theme: {
    extend: {
      fontFamily: {
        'body-large': 'var(--body-large-font-family)',
        'body-large-bold': 'var(--body-large-bold-font-family)',
        'body-medium': 'var(--body-medium-font-family)',
        'body-medium-bold': 'var(--body-medium-bold-font-family)',
        'body-small': 'var(--body-small-font-family)',
        'body-small-bold': 'var(--body-small-bold-font-family)',
        'body-xsmall': 'var(--body-xsmall-font-family)',
        'body-xsmall-bold': 'var(--body-xsmall-bold-font-family)',
        'display-large': 'var(--display-large-font-family)',
        'display-medium': 'var(--display-medium-font-family)',
        'display-small': 'var(--display-small-font-family)',
        'heading-large': 'var(--heading-large-font-family)',
        'heading-medium': 'var(--heading-medium-font-family)',
        'heading-small': 'var(--heading-small-font-family)',
        'heading-xlarge': 'var(--heading-xlarge-font-family)',
        'heading-xsmall': 'var(--heading-xsmall-font-family)',
        'heading-xxsmall': 'var(--heading-xxsmall-font-family)',
        'label-large': 'var(--label-large-font-family)',
        'label-medium': 'var(--label-medium-font-family)',
        'label-small': 'var(--label-small-font-family)',
        'label-xsmall': 'var(--label-xsmall-font-family)',
        'navigation-depth-medium': 'var(--navigation-depth-medium-font-family)',
        'navigation-depth-medium-bold': 'var(--navigation-depth-medium-bold-font-family)',
        'navigation-depth-small': 'var(--navigation-depth-small-font-family)',
        'navigation-depth-small-bold': 'var(--navigation-depth-small-bold-font-family)',
        'navigation-title-medium': 'var(--navigation-title-medium-font-family)',
        'navigation-title-small': 'var(--navigation-title-small-font-family)',
        'underline-large': 'var(--underline-large-font-family)',
        'underline-medium': 'var(--underline-medium-font-family)',
        'underline-small': 'var(--underline-small-font-family)',
        'underline-xsmall': 'var(--underline-xsmall-font-family)',
        sans: [
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          'Apple Color Emoji"',
          'Segoe UI Emoji"',
          'Segoe UI Symbol"',
          'Noto Color Emoji"',
        ],
      },
      boxShadow: {
        'shadow-1': 'var(--shadow-1)',
        'shadow-2': 'var(--shadow-2)',
        'shadow-3': 'var(--shadow-3)',
        'shadow-4': 'var(--shadow-4)',
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
  darkMode: ['class'],
};
